### ISSUE TITLE
"Load external jars" in Analysis tab not working on JDK9+

### ISSUE THREAD

**Issue by mocobeta** [DmitryKey/luke#138]
From log:
```
[2018-10-13 19:40:11,442] ERROR (ExceptionHandler.java:36) - class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at org.apache.lucene.luke.models.analysis.AnalysisImpl.addURLToSystemClassLoader(AnalysisImpl.java:107)
	at org.apache.lucene.luke.models.analysis.AnalysisImpl.addExternalJars(AnalysisImpl.java:90)
	at org.apache.lucene.luke.app.desktop.components.AnalysisPanelProvider$AnalysisPanelOperatorImpl.addExternalJars(AnalysisPanelProvider.java:129)
	at org.apache.lucene.luke.app.desktop.components.fragments.analysis.CustomAnalyzerPanelProvider$ListenerFunctions.lambda$loadExternalJars$0(CustomAnalyzerPanelProvider.java:145)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.apache.lucene.luke.app.desktop.components.fragments.analysis.CustomAnalyzerPanelProvider$ListenerFunctions.loadExternalJars(CustomAnalyzerPanelProvider.java:144)
	at org.apache.lucene.luke.app.desktop.components.fragments.analysis.CustomAnalyzerPanelProvider$1.mouseClicked(CustomAnalyzerPanelProvider.java:451)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

And, forbiddenapi checker (#115)  complains as follows:
```
[ERROR] Forbidden method invocation: java.lang.reflect.AccessibleObject#setAccessible(boolean) [Reflection usage to work around access flags fails with SecurityManagers and likely will not work anymore on runtime classes in Java 9]
[ERROR]   in org.apache.lucene.luke.models.analysis.AnalysisImpl (AnalysisImpl.java:112)
```

**Comment by mocobeta** [comment]
https://stackoverflow.com/questions/46694600/java-9-compatability-issue-with-classloader-getsystemclassloader

**Comment by mocobeta** [comment]
Confirmed on JDK11.
