### ISSUE TITLE
The Luke can't show the field of the term count for  Long、Date type.

### ISSUE THREAD

**Issue by changquanyou** [DmitryKey/luke#186]
I  use ElasticSearch-v6.0.0, and the luence version is 7.0.1, of course, the luke can open the index, but it has some issues, maybe  it's my fault。here is the description:
- ES Mapping
   I just show the long type for createTime field:
      `"createTime": {"type": "long"}`
- Open Index With Luke
   it shows the Term Count =0 in createTime field, it has some error it log:
   `Caused by: java.lang.RuntimeException: field createTime not found
	at org.apache.lucene.misc.HighFreqTerms.getHighFreqTerms(HighFreqTerms.java:104) ~[lucene-misc-8.6.1.jar:8.6.1 6e11a1c3f0599f1c918bc69c4f51928d23160e99 - houstonputman - 2020-08-10 13:29:13]
	at org.apache.lucene.luke.models.overview.TopTerms.getTopTerms(TopTerms.java:56) ~[lucene-luke-8.6.1.jar:8.6.1 6e11a1c3f0599f1c918bc69c4f51928d23160e99 - houstonputman - 2020-08-10 13:29:12]
	at org.apache.lucene.luke.models.overview.OverviewImpl.getTopTerms(OverviewImpl.java:165) ~[lucene-luke-8.6.1.jar:8.6.1 6e11a1c3f0599f1c918bc69c4f51928d23160e99 - houstonputman - 2020-08-10 13:29:12]`

**Comment by changquanyou** [comment]
I‘m very confused， Thank you for answering my questions

**Comment by DmitryKey** [comment]
hey @changquanyou does Elasticsearch open your index fine? Can you try with a luke version closer to your Lucene index version, for instance: https://github.com/DmitryKey/luke/releases/tag/luke-7.1.0

**Comment by mocobeta** [comment]
Yes it's expected.

> The Luke can't show the field of the term count for Long、Date type. 

Long or Date type is not "term" (they are represented by different data structure from terms), so can't count their occurrences as term. Once you understand Lucene internal a little, it would be very clear to you why the error occurs.

Nonetheless, the runtime exception might be confusing for Lucene newbies; we should have better message in the UI.
