### ISSUE TITLE
IndexFormatTooNewException while using luke-4.6.0-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by smadha** [DmitryKey/luke#41]
$ java -jar ../../luke-4.6.0-jar-with-dependencies.jar -index geoIndex/ 

org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource: ChecksumIndexInput(NIOFSIndexInput(path="/lucene-geo-gazetteer/geoIndex/segments_1"))): 4 (needs to be between 0 and 1)
	at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:148)
	at org.apache.lucene.index.SegmentInfos.read(SegmentInfos.java:329)
	at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:404)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:843)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:694)
	at org.apache.lucene.index.SegmentInfos.read(SegmentInfos.java:400)
	at org.getopt.luke.Luke.openIndex(Luke.java:868)
	at org.getopt.luke.Luke.startLuke(Luke.java:5210)
	at org.getopt.luke.Luke.main(Luke.java:5237)

Can you please suggest anything? 

How I built my index?
I followed -> https://github.com/chrismattmann/lucene-geo-gazetteer which in turn uses lucene 5.0.0 to build index. Does it works with lucene 5.0.0?

Thanks a lot in advance.
Madhav

**Comment by smadha** [comment]
Works with latest release. https://github.com/DmitryKey/luke/releases/tag/luke-5.3.0

Awesome! Thanks for this :)

**Comment by DmitryKey** [comment]
You are welcome :)
