### ISSUE TITLE
NoSuchMethodException: PrefixQuery.getTermsEnum when using "Explain structure"

### ISSUE THREAD

**Issue by OlivierJaquemet** [DmitryKey/luke#84]
To reproduce : 
- open a valid lucene index with luke
- access _Search_ tab
- enter the following query (replace `field_name` with a valid text field name of the index, and replace `text` with a known term of the index)
```
    field_name:text*
```
- click button _Explain structure_

Bug occurs :
- the UI display the following dialog (whereas a list of term starting with the specified text is expected)
![image](https://cloud.githubusercontent.com/assets/618861/23949121/5520f558-0986-11e7-9f2d-7161df09a1ac.png)
- the following exception occurs in the log
```
java.lang.NoSuchMethodException: org.apache.lucene.search.PrefixQuery.getTermsEnum(org.apache.lucene.index.Terms, org.apache.lucene.util.AttributeSource)
        at java.lang.Class.getDeclaredMethod(Class.java:2130)
        at org.getopt.luke.Luke.addTermsEnum(Luke.java:4498)
        at org.getopt.luke.Luke._explainStructure(Luke.java:4204)
        at org.getopt.luke.Luke.explainStructure(Luke.java:4141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at thinlet.Thinlet.invokeImpl(Thinlet.java:4579)
        at thinlet.Thinlet.invoke(Thinlet.java:4546)
        at thinlet.Thinlet.handleMouseEvent(Thinlet.java:3937)
        at thinlet.Thinlet.processEvent(Thinlet.java:2917)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by OlivierJaquemet** [comment]
(PR coming soon)
