### ISSUE TITLE
Error when trying to open lucene index of version 4.X

### ISSUE THREAD

**Issue by yossivainshtein** [DmitryKey/luke#96]
Hi,
Is luke currently not backward-compatible?
I'm trying to open an index created with lucene 4.10.3 with the latest luke, and getting  this error:

org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="/Users/yossiv/index/segments_3"))): 3 (needs to be between 6 and 7). This version of Lucene only supports indexes created with release 6.0 and later.
	at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:213)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:305)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:289)
	at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:427)
	at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:424)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:670)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:622)
	at org.apache.lucene.index.SegmentInfos.readLatestCommit(SegmentInfos.java:429)
	at org.getopt.luke.Luke.openIndex(Luke.java:898)
	at org.getopt.luke.Luke.openOk(Luke.java:717)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at thinlet.Thinlet.invokeImpl(Thinlet.java:4579)
	at thinlet.Thinlet.invoke(Thinlet.java:4546)
	at thinlet.Thinlet.handleMouseEvent(Thinlet.java:3937)
	at thinlet.Thinlet.processEvent(Thinlet.java:2917)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by DmitryKey** [comment]
Hi @yossivainshtein 

This is not luke being not backwards compatible, this is Lucene, that luke uses. In order to load 4.10.3 use [luke-4.10.3](https://github.com/DmitryKey/luke/releases/tag/luke-4.10.3).
